config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :post_attachments
  resources :posts

  root 'posts#index'

  get 'homes/index'
  get 'searches/result'
  get 'pages/about'
  get 'pages/mypage'
  get 'pages/ad'
  get 'pages/privacy'
  get 'pages/customer'
  get 'pages/rules'
  # 해시태그
  get '/posts/hashtag/:name', to: 'posts#hashtags'

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  resources :comments, only: [:create, :destroy]

  # 항상 맨 아래에 위치시킴
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def result
    @searches = eval(params[:bulletin]).where('created_at >= :years_ago', :years_ago => Time.now - 1.years).where("title like ?", "%#{params[:search_text]}%")
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_form.html.erb
<%= form_tag(searches_result_path, method: "get") do %> <%# method를 get방식으로 받아내며, parameter가 /searches/result로 넘어갈 예정. %>
    <%= text_field_tag :search_text, nil, placeholder: '찾고 싶은 레시피를 검색 하세요.' %> <%# 검색 하고자 하는 단어를 입력받음, 이 떄 name은 [검색 단어] %>
    <%= hidden_field_tag(:bulletin, "#{post}") %> <%# 모델 이름을 자동으로 받아냄 (name은 [bulletin], value 값에는 [모델 이름]이 들어감) %>
    <%= button_tag(type: 'submit') do %>
     <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    <% end %>
<% end %>

app/views/searches/result.html.erb
<h2 class="text-center" style="margin-top: 30px;">검색 결과</h2>

<div class="container">
  <% @searches.each do |post| %>
  <div class="col-md-3">
    <div class="recipe-box">
    <%= link_to (image_tag post.image.url, class: "recipe-index"), post %>
      <ul>
        <li><%= post.title %></li>
        <div class="option">
          <div class="index-temperature">
          온도<br>
            <div class="text-temperature">
            <%= post.temperature %>
            </div>
          </div>
          <div class="index-time">
          시간<br>
            <div class="text-time">
            <%= post.time %>
            </div>
          </div>
        </div>
      </ul>
    </div> <!--/recipe-box-->
  </div> <!--/col-md-3-->
  <% end %>
  <% if @searches.all.empty? %>
    <h3 class="text-center" style="margin-top: 30px;">레시피가 없습니다.</h3>
  <% end %>
  <%= @test %>
</div>