config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :post_attachments
  resources :posts

  root 'posts#index'

  get 'homes/index'
  get 'searches/result'
  get 'pages/about'
  get 'pages/mypage'
  get 'pages/ad'
  get 'pages/privacy'
  get 'pages/customer'
  get 'pages/rules'
  # 해시태그
  get '/posts/hashtag/:name', to: 'posts#hashtags'

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  resources :comments, only: [:create, :destroy]

  # 항상 맨 아래에 위치시킴
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/post.rb
class Post < ApplicationRecord
  resourcify
  is_impressionable


  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true

  mount_uploader :image, ImageUploader

  has_many :post_attachments
  accepts_nested_attributes_for :post_attachments

  has_many :likes, dependent: :destroy

  belongs_to :user
  acts_as_commentable

  belongs_to :category

  # paginates_per 4

  # 해시태그 DB 모델관계 설정
  has_and_belongs_to_many :tags

  after_create do
      post = Post.find_by(id: self.id)
      hashtags = self.description.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
      hashtags.uniq.map do |hashtag|
          tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
          post.tags << tag
      end
  end

  before_update do
      post = Post.find_by(id: self.id)
      post.tags.clear
      hashtags = self.description.scan(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/)
      hashtags.uniq.map do |hashtag|
          tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
          post.tags << tag
      end
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # 조회수
  impressionist actions: [:show]
  # , unique: [:ip_address] 서비스 시 위의 코드와 결합

  def hashtags
      tag = Tag.find_by(name: params[:name])
      @posts = tag.posts
      @posts = Post.order("created_at DESC").page(params[:page]).per(4)
  end

  def like_toggle
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    if like.nil? # 좋아요가 없다면?
      Like.create(user_id: current_user.id, post_id: params[:post_id])
    else # 좋아요가 있다면?
      like.destroy
    end
    redirect_to posts_url
  end

  # GET /posts
  # GET /posts.json
  def index
    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @posts = Post.where(category: @category)
      @posts = Post.order("created_at DESC").page(params[:page]).per(4)
    else
      @posts = Post.all
      @posts = Post.order("created_at DESC").page(params[:page]).per(4)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_attachments = @post.post_attachments.all

    @post = Post.find(params[:id])
    @new_comment = Comment.build_from(@post, current_user.id, "")
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        params[:post_attachments]['avatar'].each do |a|
           @post_attachment = @post.post_attachments.create!(:avatar => a)
        end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post][:user_id] = current_user.id
      params.require(:post).permit(:likes, :category_id, :nickname, :user_id, :remove_image, :image, :title, :description, :temperature, :time, ingredients_attributes:[:id, :content, :_destroy], steps_attributes:[:id, :direction, :_destroy], post_attachments_attributes: [:id, :post_id, :avatar],)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def render_with_hashtags(description)
      description.gsub(/[#＃][a-z|A-Z|가-힣|0-9|\w]+/){|word| link_to word, "/posts/hashtag/#{word.delete("#")}"}.html_safe
  end

end

app/views/posts/_common_index.html.erb
<p id="notice"><%= notice %></p>

  <div class="container" style="text-align: right;">

    <div class="main-category">
      <% Category.all.each do |p| %>
        <%= link_to p.name, posts_path(category: p.name) %>
      <% end %>
    </div>

    <div class="search-button">
      <%= render 'searches/search_form', post: @posts.klass %>
    </div>

    <div class="row">
      <% @posts.each do |post| %>
      <div class="col-md-3">
        <div class="recipe-box">
            <% if post.image? %>
              <%= link_to (image_tag post.image.url, class: "recipe-index"), post %>
            <% end %>
          <ul>
            <li><%=link_to post.title, post %></li>
              <div class="option">
                <div class="index-temperature">
                  온도<br>
                  <div class="text-temperature">
                  <%= post.temperature %>
                  </div>
                </div>
                <div class="index-time">
                  시간<br>
                  <div class="text-time">
                  <%= post.time %>
                  </div>
                </div>
                <div class="option-count">
                  <i class="fas fa-heart"></i>
                  <%= post.likes.size %>
                  <i class="fas fa-eye" style="padding-left: 5px;"></i>
                  <%= "#{post.impressionist_count}" %>
                </div>
              </div>
            <!-- <li>
              <%= link_to 'Show', post %>
              <%= link_to 'Edit', edit_post_path(post) %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </li> -->
          </ul>
        </div> <!--/recipe-box-->
      </div> <!--/col-md-3-->
      <% end %>
      <div class="post-paginate">
        <%= paginate @posts %>
      </div>
    </div> <!--/row-->
  </div> <!--/container-->
<br>

app/views/posts/_form.html.erb
<div style="background-color: rgba(240, 240, 241, 0.49);">
  <div class="container">
    <div class="main-text">
      나만의 레시피 공유하기
    </div>

    <div class="sub-text">
      <p>여러분의 에어프라이어 레시피를 공유해주세요.</p>
      <p>누군가에게 만찬을 선사할 수도 있습니다.</p>
    </div>

    <%= form_with(model: post, local: true) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="col-8">
          <div class="form-group">
            <p>대표 이미지</p>
            <%= form.file_field :image %>

            <% if @post.image? %>
              <%= image_tag @post.image.url %>
              <%= form.check_box :remove_image %> 삭제하기
            <% end %>
          </div>

          <div class="form-group">
            <%= form.fields_for :post_attachments do |p| %>
                <p>추가 이미지</p>
                <%= p.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]" %>
            <% end %>
          </div>
        </div> <!-- col-8 -->

        <div class="col-4" style="border-left: 1px solid rgba(201,201,201,0.8);">
          <div class="form-group">
            <p>레시피 이름</p>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group">
            <p>레시피 종류</p>
            <%= form.collection_select :category_id, Category.all, :id, :name %>
          </div>

          <div class="form-group">
            <p>레시피 온도</p>
            <%= form.number_field :temperature, class: "form-control" %>
          </div>

          <div class="form-group">
            <p>레시피 시간</p>
            <%= form.number_field :time, class: "form-control" %>
          </div>
        </div> <!-- col-4 -->
      </div> <!-- row -->

      <div class="form-group">
        <p>레시피 코멘트</p>
        <%= form.text_area :description, class: "form-control" %>
      </div>


      <div class="form-group">
        <p>레시피 재료</p>
        <%= form.nested_fields_for :ingredients do |ingredient| %>
          <%= ingredient.text_field :content %>
          <%= ingredient.remove_nested_fields_link '삭제하기', data: { confirm: '정말 삭제하시겠습니까?' } %>
        <% end %>
        <%= form.add_nested_fields_link :ingredients, "+ 추가하기", class: "form-control" %>
      </div>


      <div class="form-group">
        <p>레시피 방법</p>
        <%= form.nested_fields_for :steps do |step| %>
          <%= step.text_field :direction %>
          <%= step.remove_nested_fields_link '삭제하기', data: { confirm: '정말 삭제하시겠습니까?' } %>
        <% end %>
        <%= form.add_nested_fields_link :steps, "+ 추가하기", class: "form-control" %>
      </div>


      <div class="actions" style="text-align: center;">
        <%= form.submit "나만의 레시피 공유하기", class: "form-submit-button" %>
      </div>
    <% end %>
  </div> <!-- container -->
</div> <!-- background-color -->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/hashtags.html.erb
<%= render 'posts/common_index' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div id="wrap">
  <div class="container">
    <div class="create-button">
      <%= link_to '레시피 공유하기', new_post_path %>
      <%= render 'searches/search_form', post: @posts.klass %>
    </div>
    <div class="row">
      <% @posts.each do |post| %>
      <div class="col-md-3">
        <div class="recipe-box">
          <% if post.image? %>
            <%= link_to (image_tag post.image.url, class: "recipe-index"), post %>
          <% end %>
          <ul>
            <li><%= post.title %></li>
              <div class="option">
                <div class="index-temperature">
                  온도<br>
                  <div class="text-temperature">
                  <%= post.temperature %>
                  </div>
                </div>
                <div class="index-time">
                  시간<br>
                  <div class="text-time">
                  <%= post.time %>
                  </div>
                </div>
                <%= post.user.email %>
              </div>
            <!-- <li>
              <%= link_to 'Show', post %>
              <%= link_to 'Edit', edit_post_path(post) %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            </li> -->
          </ul>
        </div> <!--/recipe-box-->
      </div> <!--/col-md-3-->
      <% end %>
    </div> <!--/row-->
  </div> <!--/container-->
</div> <!--/wrap-->
<br>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>
<!-- 
<%= link_to 'Back', posts_path %> -->

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div style="background-color: rgba(240, 240, 241, 0.49);">
  <div class="container">


      <div class="row">
        <div class="col-8">
          <div class="form-group">
            <p>대표 이미지</p>
            <% if @post.image? %>
              <%= image_tag @post.image.url(:thumb) %>
            <% end %>
          </div>

          <div class="form-group">
                <p>추가 이미지</p>
                <% @post_attachments.each do |p| %>
                  <%= image_tag p.avatar_url(:thumb) %>
                  <%= link_to "수정하기", edit_post_attachment_path(p) %>
                <% end %>
          </div>
        </div> <!-- col-8 -->

        <div class="col-4" style="border-left: 1px solid rgba(201,201,201,0.8);">
          <div class="form-group">
            <p>레시피 이름</p>
            <%= @post.title %>
          </div>

          <div class="form-group">
            <p>레시피 종류</p>
            <%= @post.category.name %>
          </div>

          <div class="form-group">
            <p>레시피 온도</p>
            <%= @post.temperature %>
          </div>

          <div class="form-group">
            <p>레시피 시간</p>
            <%= @post.time %>
          </div>
          <p>
            <strong>Like:</strong>
            <%= @post.likes.size %> 명이 좋아합니다.
          </p>

          <p>
            <% if Like.find_by(user_id: current_user.id, post_id: @post.id) %>
              <%= link_to("좋아요 취소","/likes/#{@post.id}/destroy",{method: "post"}) %>
            <% else %>
              <%= link_to("좋아요", "/likes/#{@post.id}/create", {method: "post"}) %>
            <% end %>
          </p>
        </div> <!-- col-4 -->
      </div> <!-- row -->

      <div class="form-group">
        <p>레시피 코멘트</p>
        <%= render_with_hashtags(@post.description) %>
      </div>


      <div class="form-group">
        <p>레시피 재료</p>
        <% for @ingredient in @post.ingredients %>
          <li><%= @ingredient.content %></li>
        <% end %>
      </div>


      <div class="form-group">
        <p>레시피 방법</p>
        <% for @step in @post.steps %>
          <li><%= @step.direction %></li>
        <% end %>
      </div>

      <%= render partial: "comments/template", locals: {commentable: @post, new_comment: @comment} %>

      <div style="float: left">
        <%= link_to '목록', posts_path %>
        <% if can? :update, @post %>
        <%= link_to '수정', edit_post_path(@post) %>
        <% end %>
        <% if can? :destroy, @post %>
        <%= link_to '삭제', @post, method: :delete, method: :delete, data: { confirm: '진짜로 지울건가요???' } %>
        <% end %>
      </div>

  </div> <!-- container -->
</div> <!-- background-color -->