config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :post_attachments
  resources :posts

  root 'posts#index'

  get 'homes/index'
  get 'searches/result'
  get 'pages/about'
  get 'pages/mypage'
  get 'pages/ad'
  get 'pages/privacy'
  get 'pages/customer'
  get 'pages/rules'
  # 해시태그
  get '/posts/hashtag/:name', to: 'posts#hashtags'

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  resources :comments, only: [:create, :destroy]

  # 항상 맨 아래에 위치시킴
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/views/layouts/_footer.html.erb
  <!-- Site footer -->
  <footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h6>회사소개</h6>
          <li style="list-style: none" class="text-justify">(주)유니스퀘어 / 사업자등록번호 444-86-00863</li>
          <li style="list-style: none" class="text-justify">대표 : OOO</li>
          <li style="list-style: none" class="text-justify">문의 : help@iwantairfryer.com</li>
          <li style="list-style: none" class="text-justify">위치 : 서울 강남구 테헤란로 113 목화밀라트 1811호</li>
          <br>
          <li style="list-style: none" class="text-justify"> 통신판매업신고 / 제 2019-서울강남-OOOO호</li>
          <li style="list-style: none" class="text-justify"> <a href="http://www.ftc.go.kr/www/bizCommList.do?key=232" target="_blank">사업자정보확인</a></li>

        </div>

        <div class="col-xs-6 col-md-3">
          <h6>B.R.G.G</h6>
          <ul class="footer-links">
            <li><a href="#">레시피 제보</a></li>
            <li><a href="#">UI Design</a></li>
            <li><a href="#">PHP</a></li>
            <li><a href="#">Java</a></li>
            <li><a href="#">Android</a></li>
            <li><a href="#">Templates</a></li>
          </ul>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>바로가기 </h6>
          <ul class="footer-links">
            <li><%= link_to "회사소개", pages_about_path %></li>
            <li><%= link_to "광고문의", pages_ad_path %></li>
            <li><%= link_to "개인정보처리방침", pages_privacy_path %></li>
            <li><%= link_to "고객센터", pages_customer_path %></li>
            <li><%= link_to "이용약관", pages_rules_path %></li>
          </ul>
        </div>
      </div>
      <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-6 col-xs-12">
          <p class="copyright-text">Copyright &copy; 2019 All Rights Reserved by
       <a href="#">에어프라이어 나만없어</a>.
          </p>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
          <ul class="social-icons">
            <li><a class="facebook" href="https://www.facebook.com/iwantairfryer/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
            <li><a class="instagram" href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a class="youtube" href="#" target="_blank"><i class="fab fa-youtube"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="padding-bottom: 20px;">
  <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  <!-- <%= link_to "에어프라이어 나만없어", root_path, class: 'navbar-brand' %> -->
  <%= link_to(image_tag("main_logo.png"), root_path, class: 'navbar-brand') %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent" style="width: 600px;">
    <div class="login-info">
      <div class="welcome">
      <% if current_user %>
        <% if current_user.name %>
        <%= link_to current_user.name, pages_mypage_path  %> 님 반갑습니다 <br>
        <% else current_user.nickname %>
        <%= link_to current_user.nickname, pages_mypage_path %> 님 반갑습니다 <br>
        <% end %>
      </div>
      <div class="login-info-text">
        <!-- <%= link_to '로그아웃', destroy_user_session_path, method: :delete %> /
        <%= link_to '마이페이지', pages_mypage_path %> -->
        <% else %>
        <%= link_to '로그인', new_user_session_path %> /
        <%= link_to '회원가입', new_user_registration_path %>
        <% end %>
      </div>
      <div class="create-button">
        <%= link_to '레시피 공유하기', new_post_path %>
      </div>

    </div>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <title>에어프라이어</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
    function showHide(id) {
       var obj = document.getElementById(id);
       if (obj.style.display == 'none')
           obj.style.display = 'block';
       else
           obj.style.display = 'none';
    }
    </script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  </body>
  <%= yield %>
  <%= render 'layouts/footer' %>
</html>